### ISSUE TITLE
TWS Connection doesn't work

### ISSUE THREAD

**Issue by BigKahunaCanuck** [wboayue/rust-ibapi#157]
TWS API (port 7497) throws errors when running https://github.com/wboayue/rust-ibapi/blob/main/examples/market_data.rs
 ERROR ibapi::transport] error reading next message (shutting down): Io(Os { code: 10060, kind ...

The code works fine with the Gateway.

This means one needs to disconnect from the Desktop to log into the Gateway.

**Comment by wboayue** [comment]
Was not able to reproduce this with TWS or the Gateway on my system. I suspect this is because TWS uses more resources and may slow responses on your system. Updated the main branch to allow more time to receive data. Give that a try.

**Comment by wboayue** [comment]
Also are you on a Windows machine? I'm on a Mac, it might be something platform specific.

**Comment by BigKahunaCanuck** [comment]
I think I am running into a pacing violation.  What I am working on is custom scanners and I'm looking at ~600 symbols.  When I add sleep time, it gets further.  I need to explore smarter pacing strategies.

**Comment by BigKahunaCanuck** [comment]
Yes, Windows.

**Comment by wboayue** [comment]
Code updated to handle Windows specific codes.
