### ISSUE TITLE
Client::completed_orders freezes since v0.5.0

### ISSUE THREAD

**Issue by drpngx** [wboayue/rust-ibapi#194]
Repro: spawn an ibgateway on port `4001` and add to `client.rs`:
```
mod tests {
    use super::*;

  #[test]
  fn try_completed_orders() {
    let client = Client::connect("127.0.0.1:4001", 0).unwrap();
    println!("connected");
    let sub = client.completed_orders(false).unwrap();
    println!("Got sub");
    for or in sub.into_iter() {
      println!("or: {:?}", or);
    }
  }
}
```
Run: `cargo test client::tests::try_completed_orders -- --nocapture`
It prints `Got sub` then freezes. `Subscription::next` is never called. `decode_completed_order` is never called.
I tested on release `v0.5.0`, where it works, and `v1.0.0`, where it doesn't. 
After some bisection: 
```
d3266a5 @ simplify retry (#131) -> freeze
3921d68 @ Implements request positions multi (#121) -> panic
d48c259 @ Refactor response iterators (#120) -> panic
1ec6d61 @ Adds request PNL APIs (#119) -> pass
```
So it passed, until #119, then panic in `transport.rs` is introduced in #120 and at some point before #131 it turns into a freeze.

With `IBAPI_RECORDING_DIR` on, the preambles are slightly different but the req is the same, but they get different responses.
```
Request: 99|0|  aka ReqCompletedOrders(api_only=0)
v0.5.0:  102|| aka CompledOrdersEnd
v1.0.5: Response: 9|1|938|| aka NextValidOrder
```

**Comment by wboayue** [comment]
This is actually working as designed. Review the behavior of subscriptions [here](https://docs.rs/ibapi/latest/ibapi/client/struct.Subscription.html). 

Previously iterators automatically timed out after 10 seconds while waiting for a response. This works ok when placing and checking the status of order with immediate fills such as markets orders. If placing and checking the status of a limit order that took a while to fill the application had no way to specify how long it wanted to wait. The subscription interface addresses this issue.

By default the subscription will create an iterator that blocks forever. To replicate the previous behavior, your code would look like this.

```rust
mod tests {
    use super::*;

  #[test]
  fn try_completed_orders() {
    let client = Client::connect("127.0.0.1:4001", 0).unwrap();
    println!("connected");
    let sub = client.completed_orders(false).unwrap();
    println!("Got sub");
    for or in sub.timeout_iter(Duration::from_secs(10)) {
      println!("or: {:?}", or);
    }
  }
}
```

**Comment by wboayue** [comment]
Also in the previous scenario you can also break out of the loop after processing the messages you were expecting.

**Comment by wboayue** [comment]
Thanks for reporting this. Initially misunderstood the issue.

Have a PR to fix this https://github.com/wboayue/rust-ibapi/pull/195/files. Will create a new release after more testing.

**Comment by drpngx** [comment]
Thank you for the tips and quick resolution!
