### ISSUE TITLE
WSH Enhancements

### ISSUE THREAD

**Issue by BigKahunaCanuck** [wboayue/rust-ibapi#208]
It would be very helpful to have an iterator for the WshEventData instead of having to parse the JSON.  I would like to only get earnings related data.

**Comment by wboayue** [comment]
It would probably be helpful if a Rust model was defined for the `WshEventData`.  While the event container is generic, the data element varies for each event type. Defining and maintaining this model would be it's own project. With that defined you will still need to iterate over the model to find what you're looking for.

You can probably accomplish what you want using [serde_json](https://docs.rs/serde_json/latest/serde_json/index.html) to parse the json and [serde_json_path](https://docs.rs/serde_json_path/latest/serde_json_path/) to query it.

For example:

```rust
use serde_json::Value;
use serde_json_path::JsonPath;

let wsh_text = "{}";  // Replace with the WSH event data from API call
let wsh_json: Value = serde_json::from_str(&wsh_text).unwrap();

// Define a JSONPath to select the 'data' field where 'event_type' is 'wshe_eps'
let path = JsonPath::parse("$..[?(@.event_type == 'wshe_eps')].data").unwrap();
let nodes = path.query(&wsh_json).all();

// 'nodes' now contains the 'data' field for all earnings-related events
```

The [serde_json_path online utility](https://serdejsonpath.live/) is helpful for experimenting with queries.

**Comment by BigKahunaCanuck** [comment]
Thanks Wil.  Got it working with serdejson.  You da man!
