### ISSUE TITLE
Request WSH event metadata

### ISSUE THREAD

**Issue by wboayue** [wboayue/rust-ibapi#61]
Requests metadata from the WSH calendar.

[documentation](https://interactivebrokers.github.io/tws-api/classIBApi_1_1EClient.html#a66b482661e36604c43c4a7087bd7840f)

**Comment by BigKahunaCanuck** [comment]
Any progress on this enhancement.  I could really use the earnings date for a stock.

**Comment by wboayue** [comment]
This is one of the last features I plan to implement before finalizing the next release. I want to get the release out in the next week or so.

**Comment by BigKahunaCanuck** [comment]
Great.  I have a bunch of coding to do in the meantime.  I can wait a week or two.  So long as your "so" doesn't stretch out too far.
