### ISSUE TITLE
Examples of getting different tick types as RT Volume

### ISSUE THREAD

**Issue by Pl0414141** [wboayue/rust-ibapi#98]
Hi,

Can you provide a minimal example of getting RT Volume (tickid 48) or another of list as Trade Count (tickid 54) with the aim of know how create a code to get these type of ticks?

https://interactivebrokers.github.io/tws-api/tick_types.html

Thanks a lot!

**Comment by wboayue** [comment]
I ported the order builder is rust here https://docs.rs/ibapi/latest/ibapi/orders/order_builder/fn.bracket_order.html https://github.com/wboayue/rust-ibapi/blob/0986fa70799528e2aa9320ebb9f22b718fdd74f6/src/orders/order_builder.rs#L386

**Comment by wboayue** [comment]
This is done with the recently implemented market_data API. https://github.com/wboayue/rust-ibapi/blob/main/examples/market_data.rs
