### ISSUE TITLE
Unexpected closed connection using tick-by-tick

### ISSUE THREAD

**Issue by Pl0414141** [wboayue/rust-ibapi#99]
Hi,

To reproduce:

1. Open TWS

2. Connect using the example in this repo through tick-by-tick last data https://raw.githubusercontent.com/wboayue/rust-ibapi/main/examples/tick_by_tick.rs

3. If the client do not receive any tick between 10-20 seconds the connection is closed.

Expected result:

The client should wait for more incoming ticks, do not close the connection.

Actual result:

Connection closed.

**Comment by wboayue** [comment]
Released a new version 0.4.0 that removes timeouts from realtime streams.
